### ISSUE TITLE
Using force unital from Data.Drasil can cause vector/scalar mismatches

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1115]
The force unital from Data.Drasil is a vector, and in SSP it is used in the data definition for stress, where stress and area unitals also come from Data.Drasil but are scalars, so the resulting equation is not correct:
![image](https://user-images.githubusercontent.com/18634568/52874034-739d9d80-311e-11e9-8655-e87ed8236498.png)

**Comment by bmaclach** [comment]
Looking at this issue again, I realize that the problem is stemming from the fact that I am trying to define "normal stress" as force over area, when this should really be just plain "stress". There isn't currently a stress unital in Data.Drasil, but I could add one, and it would be a vector, so this specific mismatch would be solved.

**Comment by smiths** [comment]
@bmaclach, we have to be careful to see whether we need to distinguish normal and tangential stress.  For SSP, I'm fairly sure that we need both.  The definition of both depends on area.  The generic concept of stress is fairly well covered in a document on a family of material models:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/git-svn/SciCompAndSoftEngPapers/FamilyOfMaterialModels.pdf

Maybe something like this could give us a starting point for refining the notion of stress?

**Comment by bmaclach** [comment]
@smiths I don't have access to the SEforSC repo you linked, I get a 404 error when I try to access it.

You are right that SSP uses both normal stress and shear stress. When the stress DD is invoked, it is sometimes done so with normal stress/force, sometimes with shear stress/force, and sometimes with generic, unrefined stress/force. What makes sense to me is to define the DD in terms of the generic stress/force, but have Drasil know that the same relation applies to refinements of stress/force (as long as both stress and force are refined in the same way i.e. this relation does not hold if stress is refined as "normal" and force is refined as "shear")

**Comment by JacquesCarette** [comment]
@bmaclach You need to be on the McMaster VPN (at least) to see that, I think.  You are a member of that repository, so you should have access.

**Comment by bmaclach** [comment]
What if I'm on MacSecure? Isn't that the same effect as the VPN? We've had confusion in the past caused by me having a GitLab account from 2016 that is no longer active but still exists. Is it possible it's my old account added there? (old username was bmaclach, new one is maclachb)

**Comment by JacquesCarette** [comment]
MacSecure should be considered local.  Yes, the old account is the problem.  I think I can fix that - let me try.

**Comment by JacquesCarette** [comment]
I think I've fixed it.  You should have gotten an invitation, and you should have access now with your new id.

**Comment by bmaclach** [comment]
Yes, I have access now. Thanks!

**Comment by smiths** [comment]
Thanks @JacquesCarette.  I was just going to add Brooks.  😄

**Comment by JacquesCarette** [comment]
Is this still a live issue? @smiths @bmaclach

**Comment by bmaclach** [comment]
Yes, there still appears to be a vector/scalar mismatch in the stress DD in SSP (it's now called "Total stress" instead of "normal stress", but the mismatch is still there).

**Comment by smiths** [comment]
I'll assign the issue to me.  I don't think it is so much a Drasil issue as a what we ask Drasil to do issue.  If we add a general definition of stress and then refine that into the equations we need, I think that could work.  That would mean modifying (adding to) the SSP document.  Once I figure out what needs to be changed in SSP, I'll likely need to create other issues to get help with modifying the Drasil code.

**Comment by bmaclach** [comment]
@smiths I still like the idea of being able to refine a generic definition (like the definition of stress using vectors) to various more specific definitions (like the normal stress and tangential stress definitions). But we can't do anything like that yet, and, as you say, SSP always uses components and never actually uses the vectors. So I think the short term solution of replacing the current stress DD with a normal stress DD and a shear stress DD is good.

I'm not sure from your comment if you are suggesting that we don't re-use the Newton's law definition from Game Physics. I don't think I agree that re-using that theory model is the cause of the inconsistencies. It does require us to use the vector form of force, but, like you said, it is only used in the derivation of weight, and I don't see any problems with that use case (maybe I'm missing something). I don't think making the changes you suggested (related to the stress DDs) requires changing how we use Newton's law in any way. 

I do see that we use x and y components of force in TM:equilibrium, though I think we could replace those with normal and tangential components and it would still be correct, right?

**Comment by smiths** [comment]
Thank you for the quick reply @bmaclach.  Yes, the long term plan is to find a way to refine our generic definitions.  My proposal is just to fix the dimension imbalance of having an equation with a vector on one side and a scalar on the other.

I'm definitely not proposing that we remove Newton's second law from ssp.  I very much like that we have an example of reuse.  The reason that I highlighted Newton's law is that it is the source of the **F** that appears in the stress definition.  If we didn't have **F** = m **a**, we probably would have just defined stress as F/a, and this issue wouldn't have arisen.  (The issue would still be there, but we probably wouldn't have noticed it right away.)

I like that we use Newton's law to derive the weight.  I definitely do not want to remove it.  The more examples where we share concepts the better!  There is no problem with the weight derivation.  As an aside, it is true that when reading it, I was initially confused between the two component weight vector, and the sequence that includes the weight of each slice.  I originally read **W** as a two component vector, not a sequence of scalar values, where each value is the weight of the ith slice.  That is a separate confusion, and mostly due from me not looking at the example recently.  It doesn't help that **F** is a two component vector, but **W** has n components, where n is the number of slices.  This is an inconsistency that we don't handle exactly gracefully, but that isn't related to the current issue.  At some point we probably should find a way to convey more clearly that the equations are applied at each slice and then summarized for all slices using the "vector" notation.  

Yes, we use x and y components in the theoretical model, but when we apply that model we are applying it in the normal and tangential directions.  We don't need to change this right now, but it is a source of potential confusion for some readers.  The equilibrium equation applies to any coordinate system, but it is written down for x and y.  We could define our local normal and tangential coordinate system for each slice so that the directions are labelled x and y, but for this problem we also have the notion of a global x and y.  I don't think we need to change anything right now, but we are relying on the reader to understand that our theoretical model is the general concept of equilibrium.  The specific labels and symbols used to express it aren't what matters, but rather the concept behind it.

I don't think it would be worthwhile to change the theoretical model for equilibrium to use normal and tangential directions.  That wouldn't be as reusable as what we currently have.  Eventually we should start with Newton's second law in three dimensional space, in a general coordinate system, and then observe for static equilibrium that the acceleration is zero.  This would be the more general way to do this, but it would cause too many headaches right now for us to be that general.  Someday!  :smile:

**Comment by bmaclach** [comment]
@smiths All right, I think we are in agreement then. I agree that it's better to keep the equilibrium TM as x and y, since it is meant to be very general.

**Comment by smiths** [comment]
I'll close this issue, since the discussion has been concluded.  A new issue (#2156) has been created for updating SSP.
